steps:
  - wait

  - name: ":s3: publish binaries"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  - name: ":redhat: publish rpms"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy-legacy"

  - name: ":debian: publish debs"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "experimental"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
      GPG_SIGNING_KEY: "dev@buildkite.com"
    agents:
      queue: "deploy"
    plugins:
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.02"
          propagate-environment: true

  - name: ":docker:"
    command: ".buildkite/steps/publish-docker-images.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy-legacy"
